// client/components/Tabs-category.vue
<template>
    <div class="browse-categories mt-6">
        <ul class="flex gap-14 font-bold overflow-auto">
            <li>
                <NuxtLink class="text-light-gray hover:text-black active:text-secondary hover:underline" to="#">All
                </NuxtLink>
            </li>
            <li>
                <NuxtLink class="text-light-gray hover:text-black hover:underline" to="#">Music</NuxtLink>
            </li>
            <li>
                <NuxtLink class="text-light-gray hover:text-black hover:underline" to="#">Business</NuxtLink>
            </li>
            <li>
                <NuxtLink class="text-light-gray hover:text-black hover:underline" to="#">Hobbies</NuxtLink>
            </li>
            <li>
                <NuxtLink class="text-light-gray hover:text-black hover:underline" to="#">Sport</NuxtLink>
            </li>
            <li>
                <NuxtLink class="text-light-gray hover:text-black hover:underline" to="#">Health</NuxtLink>
            </li>
        </ul>
    </div>
</template>

// components/TabsCategory.tsx
import Link from "next/link";

export default function TabsCategory() {
  return (
    <div className="browse-categories mt-4">
      <ul className="flex gap-8 sm:gap-10 font-bold overflow-x-auto">
        <li>
          <Link
            className="text-light-gray hover:text-black active:text-secondary hover:underline"
            href="#"
          >
            All
          </Link>
        </li>
        <li>
          <Link
            className="text-light-gray hover:text-black hover:underline"
            href="#"
          >
            Music
          </Link>
        </li>
        <li>
          <Link
            className="text-light-gray hover:text-black hover:underline"
            href="#"
          >
            Business
          </Link>
        </li>
        <li>
          <Link
            className="text-light-gray hover:text-black hover:underline"
            href="#"
          >
            Hobbies
          </Link>
        </li>
        <li>
          <Link
            className="text-light-gray hover:text-black hover:underline"
            href="#"
          >
            Sport
          </Link>
        </li>
        <li>
          <Link
            className="text-light-gray hover:text-black hover:underline"
            href="#"
          >
            Health
          </Link>
        </li>
      </ul>
    </div>
  );
}
