// components/ButtonSeeMore.tsx
import Link from "next/link";

export default function ButtonSeeMore() {
  return (
    <div className="flex justify-center">
      <div className="w-2/3 sm:w-1/3 mt-8 text-center">
        <Link
          className="btn btn-outline w-full normal-case font-medium text-base"
          href="#"
        >
          See more
        </Link>
      </div>
    </div>
  );
}

// client/components/Button-see-more.vue
<template>
    <div class="flex justify-center">
        <div class="button w-1/2 md:w-1/3 mt-8 text-center">
            <NuxtLink
                class="border border-black rounded-lg hover:bg-gray px-5 py-3 block w-full text-black font-medium text-sm"
                to="#">
                See more
            </NuxtLink>
        </div>
    </div>
</template>
